import Link from "next/link";
import { ArrowRight, BarChart3, Database, ScanSearch, Sparkles } from "lucide-react";
import { getHiddenGemPlayers } from "@/data/player-service";
import { Eyebrow, GemScore, SectionHeading } from "@/components/ui";

export default async function Home() {
  const hiddenGems = await getHiddenGemPlayers();
  return <>
    <section className="hero page-width">
      <div className="hero-copy"><Eyebrow>THE NEXT EDGE IN BASEBALL</Eyebrow><h1>Find the value<br/><em>others miss.</em></h1><p>DiamondDNA uses advanced baseball analytics to uncover overlooked talent and connect today&apos;s players with statistically similar careers from baseball history.</p><div className="hero-actions"><Link href="/hidden-gems" className="button primary">Explore Hidden Gems <ArrowRight size={18}/></Link><Link href="/career-trajectory" className="button secondary">Compare Careers</Link></div><div className="trust-row"><span>DATA-DRIVEN</span><span>HISTORICALLY GROUNDED</span><span>BUILT FOR DISCOVERY</span></div></div>
      <div className="hero-visual"><div className="field-rings"><div className="diamond one"/><div className="diamond two"/><div className="diamond three"/><div className="scan-line"/></div><div className="signal-card signal-main"><span>SCORING MODEL</span><strong>—</strong><small>COMING NEXT</small></div><div className="signal-card signal-side"><ScanSearch/><div><span>DATA LAYER</span><strong>PROVIDER READY</strong></div></div><div className="coordinate">38.8895° N&nbsp;&nbsp; 77.0353° W</div></div>
    </section>
    <section className="metric-strip"><div className="page-width metrics"><div><strong>02</strong><span>DATA PROVIDERS</span></div><div><strong>03</strong><span>LIVE STAT GROUPS</span></div><div><strong>1H</strong><span>DATA CACHE WINDOW</span></div><div><strong>01</strong><span>DIFFERENT PERSPECTIVE</span></div></div></section>
    <section className="home-section page-width"><SectionHeading eyebrow="CURRENT BOARD" title={<>This season&apos;s <em>Hidden Gems</em></>} text="Players creating more value than the market recognizes." action={{href:"/hidden-gems",label:"View full rankings"}}/><div className="preview-grid">{hiddenGems.slice(0,3).map((p,i)=>{const stats=p.currentSeason; const advanced=stats.kind==="batting"?stats.opsPlus:stats.eraPlus; return <article className="preview-card" key={p.identity.slug}><div className="preview-top"><span>0{i+1}</span>{p.gemScore!==null&&<GemScore score={p.gemScore} size="sm"/>}</div><div className="team-badge large" style={{borderColor:p.accent,color:p.accent}}>{p.identity.teamCode}</div><span className="meta">{p.identity.position} · {p.identity.teamCode}</span><h3>{p.identity.name}</h3><div className="preview-stats"><div><span>WAR</span><strong>{stats.war ?? "N/A"}</strong></div><div><span>{stats.kind==="batting"?"OPS+":"ERA+"}</span><strong>{advanced ?? "N/A"}</strong></div><div><span>VALUE Δ</span><strong className="lime">{p.trend ?? "N/A"}</strong></div></div></article>})}</div></section>
    <section className="trajectory-feature"><div className="page-width trajectory-inner"><div className="trajectory-art"><div className="orbit"><Sparkles/><span className="orbit-dot a"/><span className="orbit-dot b"/><span className="orbit-dot c"/></div><div className="match-chip one">94% <span>MATCH</span></div><div className="match-chip two">89% <span>MATCH</span></div></div><div><Eyebrow>CAREER TRAJECTORY</Eyebrow><h2>History leaves<br/><em>a fingerprint.</em></h2><p>See how a player&apos;s career is taking shape—then find the historical careers that moved the same way. Context, comparison, and a deeper understanding of where they&apos;ve been.</p><div className="feature-list"><span><Database/>150+ years of historical data</span><span><BarChart3/>Age-adjusted performance curves</span></div><Link href="/career-trajectory" className="button primary">Compare Careers <ArrowRight size={18}/></Link></div></div></section>
  </>;
}
