import Link from "next/link";
import { ArrowRight, BarChart3, Database, ScanSearch, Sparkles } from "lucide-react";
import { hiddenGems } from "@/data/players";
import { Eyebrow, GemScore, SectionHeading } from "@/components/ui";

export default function Home() {
  return <>
    <section className="hero page-width">
      <div className="hero-copy"><Eyebrow>THE NEXT EDGE IN BASEBALL</Eyebrow><h1>Find the value<br/><em>others miss.</em></h1><p>DiamondDNA uses advanced baseball analytics to uncover overlooked talent and connect today&apos;s players with statistically similar careers from baseball history.</p><div className="hero-actions"><Link href="/hidden-gems" className="button primary">Explore Hidden Gems <ArrowRight size={18}/></Link><Link href="/career-trajectory" className="button secondary">Compare Careers</Link></div><div className="trust-row"><span>DATA-DRIVEN</span><span>HISTORICALLY GROUNDED</span><span>BUILT FOR DISCOVERY</span></div></div>
      <div className="hero-visual"><div className="field-rings"><div className="diamond one"/><div className="diamond two"/><div className="diamond three"/><div className="scan-line"/></div><div className="signal-card signal-main"><span>BREAKOUT SIGNAL</span><strong>94</strong><small>GEM SCORE</small></div><div className="signal-card signal-side"><ScanSearch/><div><span>PLAYER VALUE</span><strong>+18.4%</strong></div></div><div className="coordinate">38.8895° N&nbsp;&nbsp; 77.0353° W</div></div>
    </section>
    <section className="metric-strip"><div className="page-width metrics"><div><strong>1,200+</strong><span>PLAYERS ANALYZED</span></div><div><strong>150</strong><span>SEASONS OF HISTORY</span></div><div><strong>24</strong><span>PERFORMANCE SIGNALS</span></div><div><strong>01</strong><span>DIFFERENT PERSPECTIVE</span></div></div></section>
    <section className="home-section page-width"><SectionHeading eyebrow="CURRENT BOARD" title={<>This season&apos;s <em>Hidden Gems</em></>} text="Players creating more value than the market recognizes." action={{href:"/hidden-gems",label:"View full rankings"}}/><div className="preview-grid">{hiddenGems.slice(0,3).map((p,i)=><article className="preview-card" key={p.id}><div className="preview-top"><span>0{i+1}</span><GemScore score={p.gemScore} size="sm"/></div><div className="team-badge large" style={{borderColor:p.accent,color:p.accent}}>{p.teamCode}</div><span className="meta">{p.position} · {p.teamCode}</span><h3>{p.name}</h3><div className="preview-stats"><div><span>WAR</span><strong>{p.war}</strong></div><div><span>{p.advancedLabel}</span><strong>{p.advancedValue}</strong></div><div><span>VALUE Δ</span><strong className="lime">{p.trend}</strong></div></div></article>)}</div></section>
    <section className="trajectory-feature"><div className="page-width trajectory-inner"><div className="trajectory-art"><div className="orbit"><Sparkles/><span className="orbit-dot a"/><span className="orbit-dot b"/><span className="orbit-dot c"/></div><div className="match-chip one">94% <span>MATCH</span></div><div className="match-chip two">89% <span>MATCH</span></div></div><div><Eyebrow>CAREER TRAJECTORY</Eyebrow><h2>History leaves<br/><em>a fingerprint.</em></h2><p>See how a player&apos;s career is taking shape—then find the historical careers that moved the same way. Context, comparison, and a deeper understanding of where they&apos;ve been.</p><div className="feature-list"><span><Database/>150+ years of historical data</span><span><BarChart3/>Age-adjusted performance curves</span></div><Link href="/career-trajectory" className="button primary">Compare Careers <ArrowRight size={18}/></Link></div></div></section>
  </>;
}
