"use client";

import { useEffect, useRef, useState } from "react";
import { Bot, Clock3, Database, Send, ShieldCheck, Sparkles, X } from "lucide-react";
import type { AssistantAnswer, AssistantHistoryItem, AssistantIntent, AssistantPlayerKind } from "@/data/assistant/types";

interface ChatMessage{role:"user"|"assistant";content:string;intent?:AssistantIntent;result?:AssistantAnswer}
interface Props{playerId:number;playerKind:AssistantPlayerKind;playerName:string;role:"position-player"|"pitcher";providerConfigured:boolean;hasCurrentStats?:boolean;hasGemScore?:boolean;hasCareerHistory?:boolean;hasSimilarity?:boolean}

export function AskDiamondDNA({playerId,playerKind,playerName,role,providerConfigured,hasCurrentStats=false,hasGemScore=false,hasCareerHistory=false,hasSimilarity=false}:Props){
  const[open,setOpen]=useState(false),[question,setQuestion]=useState(""),[messages,setMessages]=useState<ChatMessage[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),endRef=useRef<HTMLDivElement>(null),triggerRef=useRef<HTMLButtonElement>(null),panelRef=useRef<HTMLElement>(null),inputRef=useRef<HTMLTextAreaElement>(null);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"})},[messages,loading]);
  useEffect(()=>{if(!open)return;const overflow=document.body.style.overflow;document.body.style.overflow="hidden";inputRef.current?.focus();const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape"){setOpen(false);requestAnimationFrame(()=>triggerRef.current?.focus());return}if(event.key!=="Tab"||!panelRef.current)return;const focusable=[...panelRef.current.querySelectorAll<HTMLElement>('button:not([disabled]), textarea:not([disabled]), [href], [tabindex]:not([tabindex="-1"])')];if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener("keydown",onKey);return()=>{document.body.style.overflow=overflow;document.removeEventListener("keydown",onKey)}},[open]);
  const suggestions=[...(hasCurrentStats?["Summarize his season","What are his biggest strengths?","What are his biggest statistical weaknesses?"]:[]),...(hasCareerHistory?["What was his best season?","How has he changed over the last 3 seasons?"]:[]),...(hasGemScore?["Why is his Gem Score this high?"]:[]),...(playerKind==="mlb"&&hasSimilarity?["Find similar historical players"]:playerKind==="milb"?["How has he progressed through the minors?","Which level has been his best?","How old is he compared with his current level?"]:[])].slice(0,7);
  const close=()=>{setOpen(false);requestAnimationFrame(()=>triggerRef.current?.focus())};
  async function ask(text=question){const clean=text.trim();if(!clean||loading)return;setQuestion("");setError(null);const user:ChatMessage={role:"user",content:clean};setMessages(current=>[...current,user]);setLoading(true);try{const history:AssistantHistoryItem[]=messages.slice(-8).map(message=>({role:message.role,content:message.content,intent:message.intent})),response=await fetch("/api/assistant",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerId,playerKind,question:clean,history})}),payload=await response.json() as AssistantAnswer|{error?:string};if(!response.ok)throw new Error("error"in payload&&payload.error?payload.error:"Ask DiamondDNA could not answer that question.");const result=payload as AssistantAnswer;setMessages(current=>[...current,{role:"assistant",content:result.answer,intent:result.intent,result}])}catch(reason){setError(reason instanceof Error?reason.message:"Ask DiamondDNA is temporarily unavailable.")}finally{setLoading(false)}}
  return <><button ref={triggerRef} className="ask-dna-trigger" aria-expanded={open} aria-controls="ask-diamond-dna-panel" onClick={()=>setOpen(true)}><Sparkles/> Ask DiamondDNA about {playerName}</button>{open&&<div className="ask-dna-layer" role="dialog" aria-modal="true" aria-label={`Ask DiamondDNA about ${playerName}`}><button className="ask-dna-backdrop" tabIndex={-1} aria-label="Close assistant" onClick={close}/><aside ref={panelRef} id="ask-diamond-dna-panel" className="ask-dna-panel"><header><div className="ask-dna-brand"><span><Bot/></span><div><small>PLAYER-SPECIFIC ANALYTICS</small><strong>Ask DiamondDNA</strong><p>{playerName} · Official ID {playerId}</p></div></div><button aria-label="Close assistant" onClick={close}><X/></button></header><div className="ask-dna-status"><ShieldCheck/><span>Grounded in DiamondDNA&apos;s verified player data</span></div><div className="ask-dna-messages" aria-live="polite" aria-busy={loading}>{messages.length===0&&<div className="ask-dna-welcome"><Sparkles/><h2>What do you want to know?</h2><p>Questions stay attached to {playerName}. DiamondDNA retrieves the profile&apos;s verified data before answering.</p><div className="ask-dna-suggestions">{suggestions.map(prompt=><button key={prompt} onClick={()=>ask(prompt)}>{prompt}</button>)}</div><div className="ask-dna-provider"><Database/><span>{providerConfigured?"AI phrasing configured · deterministic tools used first":"AI provider not configured · deterministic data tools remain available"}</span></div></div>}{messages.map((message,index)=><article key={`${message.role}-${index}`} className={`ask-message ${message.role}`}><span>{message.role==="assistant"?"DIAMONDDNA":"YOU"}</span><p>{message.content}</p>{message.result&&<><div className="ask-evidence">{message.result.evidence.map(item=><div key={`${item.label}-${item.value}`}><small>{item.label}</small><strong>{item.value}</strong>{item.note&&<em>{item.note}</em>}</div>)}</div><footer><Database/> {message.result.sourceLabel}{message.result.freshness&&<><Clock3/> Updated {new Date(message.result.freshness).toLocaleString()}</>}</footer></>}</article>)}{loading&&<div className="ask-thinking"><i/><i/><i/> Retrieving verified data…</div>}{error&&<div className="ask-error" role="alert">{error}</div>}<div ref={endRef}/></div><form className="ask-dna-form" onSubmit={event=>{event.preventDefault();ask()}}><textarea ref={inputRef} aria-label={`Ask a question about ${playerName}`} value={question} onChange={event=>setQuestion(event.target.value.slice(0,500))} onKeyDown={event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();ask()}}} placeholder={`Ask about ${playerName}…`} maxLength={500} rows={2}/><div><small>{question.length}/500 · {role==="pitcher"?"Pitching":"Hitting"} context</small><button disabled={!question.trim()||loading} aria-label="Send question"><Send/></button></div></form></aside></div>}</>;
}
