"use client";
import { useState } from "react";
import { ARTICLE_CATEGORIES,type Article,type ContributorIdentity } from "@/data/articles/types";
type Props={identity:ContributorIdentity|null;articles:Article[];configured:boolean};
export function ContributorDashboard({identity,articles,configured}:Props){const[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[cover,setCover]=useState("");
 async function login(form:FormData){setBusy(true);const response=await fetch("/api/contributor/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:form.get("email"),password:form.get("password")})});const data=await response.json();if(response.ok)location.reload();else setMessage(data.error);setBusy(false)}
 async function upload(file:File|null){if(!file)return;setBusy(true);const form=new FormData();form.set("image",file);const response=await fetch("/api/contributor/images",{method:"POST",body:form}),data=await response.json();if(response.ok)setCover(data.url);else setMessage(data.error);setBusy(false)}
 async function save(form:FormData){setBusy(true);const status=String(form.get("status")),payload={title:form.get("title"),excerpt:form.get("excerpt"),content:form.get("content"),coverImageUrl:cover,imageAlt:form.get("imageAlt"),category:form.get("category"),tags:String(form.get("tags")||"").split(",").map(x=>x.trim()).filter(Boolean),seoTitle:form.get("seoTitle"),seoDescription:form.get("seoDescription"),status};const response=await fetch("/api/contributor/articles",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),data=await response.json();if(response.ok)location.reload();else setMessage(data.error);setBusy(false)}
 if(!configured)return <div className="contributor-card"><h2>Publishing setup required</h2><p>Configure Supabase before contributor sign-in and publishing are enabled. Public DiamondDNA features are unaffected.</p></div>;
 if(!identity)return <form action={login} className="contributor-card contributor-login"><h2>Contributor sign in</h2><label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><button className="button primary" disabled={busy}>{busy?"Signing in…":"Sign in"}</button>{message&&<p role="alert" className="form-error">{message}</p>}</form>;
 const publish=identity.role!=="CONTRIBUTOR";return <div className="contributor-layout"><section className="contributor-card"><header><div><small>{identity.role}</small><h2>{identity.displayName}</h2></div><button onClick={async()=>{await fetch("/api/contributor/session",{method:"DELETE"});location.reload()}}>Sign out</button></header><h3>Your articles</h3>{articles.length?articles.map(a=><p className="draft-row" key={a.id}><span><strong>{a.title}</strong><small>{a.status} · {a.category}</small></span><a href={`/analysis/${a.slug}`}>{a.status==="published"?"View":"Private draft"}</a></p>):<p>No drafts yet.</p>}</section><form action={save} className="contributor-card article-editor"><h2>New article</h2><label>Headline<input name="title" required maxLength={140}/></label><label>Excerpt<textarea name="excerpt" required maxLength={320}/></label><label>Cover image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>upload(e.target.files?.[0]??null)}/></label>{cover&&<p className="upload-success">Image uploaded.</p>}<label>Image alt text<input name="imageAlt" maxLength={200}/></label><label>Article body<textarea name="content" required rows={16}/></label><div className="editor-row"><label>Category<select name="category">{ARTICLE_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label>Tags<input name="tags" placeholder="prospects, pitching"/></label></div><label>SEO title<input name="seoTitle" maxLength={70}/></label><label>SEO description<textarea name="seoDescription" maxLength={170}/></label><div className="editor-actions"><button name="status" value="draft" className="button secondary" disabled={busy}>Save draft</button>{publish&&<button name="status" value="published" className="button primary" disabled={busy}>Publish</button>}</div>{message&&<p role="alert" className="form-error">{message}</p>}</form></div>}
