"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Search } from "lucide-react";
import type { PlayerRecord, PlayerRole } from "@/data/models/player";
import { Eyebrow, PlayerCard } from "@/components/ui";

type FilterType="all"|PlayerRole;
export function HiddenGemsDashboard({initialPlayers}:{initialPlayers:PlayerRecord[]}){
  const[type,setType]=useState<FilterType>("all"),[query,setQuery]=useState(""),[position,setPosition]=useState("all"),positions=useMemo(()=>Array.from(new Set(initialPlayers.map(player=>player.identity.position))).sort(),[initialPlayers]),players=useMemo(()=>initialPlayers.filter(player=>(type==="all"||player.identity.role===type)&&(position==="all"||player.identity.position===position)&&player.identity.name.toLowerCase().includes(query.toLowerCase())),[initialPlayers,type,position,query]),isCurrentMlb=initialPlayers.length>0&&initialPlayers.every(player=>player.provenance.quality==="live"),filters:{value:FilterType;label:string}[]=[{value:"all",label:"All Players"},{value:"position-player",label:"Hitters"},{value:"pitcher",label:"Pitchers"}];
  return <div className="subpage page-width"><header className="page-header"><div><Eyebrow>DIAMONDDNA PLAYER INDEX</Eyebrow><h1>Hidden <em>Gems</em></h1><p>Finding the players whose production is ahead of their recognition.</p></div><div className="updated"><span>DATA SOURCE</span><strong>{isCurrentMlb?"MLB STATS API":"MOCK FALLBACK"}</strong><small className={isCurrentMlb?"source-live":"source-fallback"}>● {isCurrentMlb?"CURRENT MLB DATA":"FALLBACK ACTIVE"}</small></div></header><section className="method-banner"><div className="method-icon">◆</div><div><strong>Gem Score v1 · MLB-relative ranking</strong><p>Performance and Age/Upside use verified current-season MLB data. Defense, Value, and Recognition Gap remain N/A.</p></div><Link href="/methodology">Methodology <span>→</span></Link></section><div className="dashboard-bar"><div className="tabs" role="group" aria-label="Player type">{filters.map(filter=><button key={filter.value} className={type===filter.value?"active":""} onClick={()=>setType(filter.value)}>{filter.label}</button>)}</div><label className="search"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search players..." aria-label="Search players"/></label><label className="position-filter"><span>Position</span><select aria-label="Filter Hidden Gems by position" value={position} onChange={event=>setPosition(event.target.value)}><option value="all">All positions</option>{positions.map(value=><option key={value}>{value}</option>)}</select></label></div><div className="ranking-head"><span>{players.length} ELIGIBLE CURRENT-SEASON PLAYERS</span><span>RANKED BY GEM SCORE v1</span></div><div className="rankings">{players.map((player,index)=><PlayerCard player={player} rank={index+1} key={player.identity.slug}/>)}</div>{!players.length&&<div className="empty-state">No eligible players match those filters.</div>}<p className="data-note">{isCurrentMlb?"Gem Scores use verified MLB Stats API inputs. Unsupported categories remain N/A and do not reduce the score.":"MLB data could not be loaded. Mock fallback players are intentionally unscored."}</p></div>;
}
