"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Search } from "lucide-react";
import { filterPlayerIndex, type PlayerIndexFilters } from "@/data/models/player-index";
import type { IndexedPlayer } from "@/data/player-index-service";

export function PlayerDirectory({players}:{players:IndexedPlayer[]}){
  const[query,setQuery]=useState(""),[team,setTeam]=useState("all"),[position,setPosition]=useState("all"),[role,setRole]=useState<PlayerIndexFilters["role"]>("all"),[pitcherRole,setPitcherRole]=useState<PlayerIndexFilters["pitcherRole"]>("all"),[sort,setSort]=useState<PlayerIndexFilters["sort"]>("name"),[limit,setLimit]=useState(60);
  const teams=useMemo(()=>Array.from(new Map(players.map(player=>[player.teamAbbreviation,player.team])).entries()).sort((a,b)=>a[1].localeCompare(b[1])),[players]),positions=useMemo(()=>Array.from(new Set(players.map(player=>player.position))).sort(),[players]),filtered=useMemo(()=>filterPlayerIndex(players,{query,team,position,role,pitcherRole,sort}),[players,query,team,position,role,pitcherRole,sort]);
  return <><section className="directory-controls"><label className="directory-search"><Search/><input value={query} onChange={event=>{setQuery(event.target.value);setLimit(60)}} placeholder="Search any active MLB player..." aria-label="Search players"/></label><select aria-label="Filter by team" value={team} onChange={event=>setTeam(event.target.value)}><option value="all">All teams</option>{teams.map(([abbreviation,name])=><option value={abbreviation} key={abbreviation}>{name}</option>)}</select><select aria-label="Filter by position" value={position} onChange={event=>setPosition(event.target.value)}><option value="all">All positions</option>{positions.map(value=><option key={value}>{value}</option>)}</select><select aria-label="Filter by player role" value={role} onChange={event=>setRole(event.target.value as PlayerIndexFilters["role"])}><option value="all">Hitters & pitchers</option><option value="position-player">Hitters</option><option value="pitcher">Pitchers</option></select><select aria-label="Filter by pitching role" value={pitcherRole} onChange={event=>setPitcherRole(event.target.value as PlayerIndexFilters["pitcherRole"])} disabled={role==="position-player"}><option value="all">All pitching roles</option><option value="Starter">Starters</option><option value="Reliever">Relievers</option></select><select aria-label="Sort players" value={sort} onChange={event=>setSort(event.target.value as PlayerIndexFilters["sort"])}><option value="name">Sort: Name</option><option value="age">Sort: Age</option><option value="team">Sort: Team</option><option value="position">Sort: Position</option><option value="gemScore">Sort: Gem Score</option></select></section><div className="directory-summary"><span>{filtered.length} ACTIVE PLAYERS</span><span>SHOWING {Math.min(limit,filtered.length)}</span></div><div className="player-directory-grid">{filtered.slice(0,limit).map(player=><Link href={`/players/${player.mlbId}`} className="directory-player" key={player.mlbId}><span className="directory-avatar">{player.name.split(" ").map(part=>part[0]).join("").slice(0,2)}</span><span><strong>{player.name}</strong><small>{player.teamAbbreviation} · {player.position}{player.pitcherRole?` · ${player.pitcherRole}`:""}</small></span><span className="directory-meta"><b>{player.gemScore??"—"}</b><small>{player.gemScore!==null?"GEM":"AGE"} {player.gemScore===null?player.age??"N/A":""}</small></span></Link>)}</div>{limit<filtered.length&&<button className="load-more" onClick={()=>setLimit(value=>value+60)}>Load more players</button>}{!filtered.length&&<div className="empty-state">No active MLB players match those filters.</div>}</>;
}
