"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Search } from "lucide-react";
import type { MilbLevel } from "@/data/models/prospect";
import type { PlayerRole } from "@/data/models/player";

export interface ProspectDirectoryRecord{playerId:number;name:string;organization:string|null;affiliateAbbreviation:string;level:MilbLevel;position:string;role:PlayerRole;age:number|null;performance:number|null}
export type ProspectDirectoryRow=[number,string,number,string,MilbLevel,string,PlayerRole,number|null,number|null];
const levelOrder:Record<MilbLevel,number>={"Triple-A":5,"Double-A":4,"High-A":3,"Single-A":2,Rookie:1};

export function ProspectDirectory({rows,organizations}:{rows:ProspectDirectoryRow[];organizations:string[]}){
  const[query,setQuery]=useState(""),[organization,setOrganization]=useState("all"),[level,setLevel]=useState("all"),[position,setPosition]=useState("all"),[role,setRole]=useState("all"),[sort,setSort]=useState("name"),[limit,setLimit]=useState(60);
  const positions=useMemo(()=>Array.from(new Set(rows.map(row=>row[5]))).sort(),[rows]),filtered=useMemo(()=>{const normalized=query.trim().toLowerCase(),players:ProspectDirectoryRecord[]=rows.map(row=>({playerId:row[0],name:row[1],organization:row[2]<0?null:organizations[row[2]]??null,affiliateAbbreviation:row[3],level:row[4],position:row[5],role:row[6],age:row[7],performance:row[8]}));return players.filter(player=>(!normalized||player.name.toLowerCase().includes(normalized))&&(organization==="all"||player.organization===organization)&&(level==="all"||player.level===level)&&(position==="all"||player.position===position)&&(role==="all"||player.role===role)).sort((a,b)=>sort==="age"?(a.age??999)-(b.age??999)||a.name.localeCompare(b.name):sort==="level"?levelOrder[b.level]-levelOrder[a.level]||a.name.localeCompare(b.name):sort==="performance"?(b.performance??-1)-(a.performance??-1)||a.name.localeCompare(b.name):a.name.localeCompare(b.name))},[rows,organizations,query,organization,level,position,role,sort]);
  return <><section className="directory-controls prospect-controls"><label className="directory-search"><Search/><input value={query} onChange={event=>{setQuery(event.target.value);setLimit(60)}} placeholder="Search Minor League players..." aria-label="Search Minor League players"/></label><select aria-label="Filter by organization" value={organization} onChange={event=>setOrganization(event.target.value)}><option value="all">All organizations</option>{organizations.map(value=><option key={value}>{value}</option>)}</select><select aria-label="Filter by level" value={level} onChange={event=>setLevel(event.target.value)}><option value="all">All levels</option>{["Triple-A","Double-A","High-A","Single-A","Rookie"].map(value=><option key={value}>{value}</option>)}</select><select aria-label="Filter by position" value={position} onChange={event=>setPosition(event.target.value)}><option value="all">All positions</option>{positions.map(value=><option key={value}>{value}</option>)}</select><select aria-label="Filter by player role" value={role} onChange={event=>setRole(event.target.value)}><option value="all">Hitters & pitchers</option><option value="position-player">Hitters</option><option value="pitcher">Pitchers</option></select><select aria-label="Sort prospects" value={sort} onChange={event=>setSort(event.target.value)}><option value="name">Sort: Name</option><option value="age">Sort: Age</option><option value="level">Sort: Level</option><option value="performance">Sort: OPS</option></select></section><div className="directory-summary"><span>{filtered.length} MINOR LEAGUE PLAYERS</span><span>PROSPECT GEM SCORE · COMING LATER</span></div><div className="player-directory-grid">{filtered.slice(0,limit).map(player=><Link className="directory-player prospect-card" href={`/prospects/${player.playerId}`} key={player.playerId}><span className="directory-avatar">{player.name.split(" ").map(part=>part[0]).join("").slice(0,2)}</span><span><strong>{player.name}</strong><small>{player.affiliateAbbreviation} · {player.position} · {player.level}</small></span><span className="level-pill">{player.level}</span></Link>)}</div>{limit<filtered.length&&<button className="load-more" onClick={()=>setLimit(value=>value+60)}>Load more prospects</button>}{!filtered.length&&<div className="empty-state">No Minor League players match those filters.</div>}</>;
}
