import Link from "next/link";
import { notFound } from "next/navigation";
import { Award, Shield } from "lucide-react";
import { AskDiamondDNA } from "@/components/ask-diamond-dna";
import { PlayerMilestones } from "@/components/player-milestones";
import { GemScore, Stat } from "@/components/ui";
import { formatStat } from "@/data/models/player";
import { getPlayerProfile } from "@/data/player-index-service";
import { trajectoryPlayers } from "@/data/trajectory";

export default async function PlayerProfilePage({params}:PageProps<"/players/[playerId]">){
  const{playerId}=await params,id=Number(playerId);if(!Number.isInteger(id))notFound();const profile=await getPlayerProfile(id);if(!profile)notFound();
  const{identity,current,career,hiddenGemRank}=profile,stats=current?.currentSeason,isHitter=identity.role==="position-player",trajectory=trajectoryPlayers.find(p=>p.name===identity.name),providerConfigured=Boolean(process.env.DIAMONDDNA_ASSISTANT_API_KEY&&process.env.DIAMONDDNA_ASSISTANT_MODEL);
  const headers=isHitter?["Year","Team","Age","G","PA","AVG","OBP","SLG","OPS","HR","RBI","SB"]:["Year","Team","Age","G","GS","IP","ERA","WHIP","K","BB","SV"];
  return <div className="subpage page-width profile-page">
    <header className="profile-hero"><div className="profile-avatar">{identity.name.split(" ").map(part=>part[0]).join("").slice(0,2)}</div><div><span>{identity.teamAbbreviation} · {identity.position}{identity.pitcherRole?` · ${identity.pitcherRole}`:""}</span><h1>{identity.name}</h1><p>{identity.team} · Age {identity.age??"N/A"} · Bats {identity.bats??"N/A"} · Throws {identity.throws??"N/A"}</p><small>MLB ID {identity.mlbId} · MLB STATS API · ACTIVE ROSTER</small></div><div className="profile-actions">{trajectory&&<Link className="button primary" href={`/career-trajectory?player=${trajectory.id}`}>Compare Career</Link>}<Link className="button secondary" href="/players">All Players</Link></div></header>
    <AskDiamondDNA key={identity.mlbId} playerId={identity.mlbId} playerKind="mlb" playerName={identity.name} role={identity.role} providerConfigured={providerConfigured} hasCurrentStats={Boolean(stats)} hasGemScore={current?.gemScore!=null} hasCareerHistory={career.length>0} hasSimilarity={Boolean(trajectory)}/>
    <PlayerMilestones playerId={identity.mlbId}/>
    <div className="profile-layout"><section className="profile-section"><div className="profile-section-head"><h2>Current Season</h2><span>{stats?.context.season??new Date().getFullYear()} · MLB DATA</span></div><div className="profile-stat-grid">{isHitter&&stats?.kind==="batting"?<><Stat label="GAMES" value={formatStat(stats.games)}/><Stat label="PA" value={formatStat(stats.plateAppearances)}/><Stat label="AVG" value={formatStat(stats.battingAverage,{decimals:3})}/><Stat label="OBP" value={formatStat(stats.onBasePercentage,{decimals:3})}/><Stat label="SLG" value={formatStat(stats.sluggingPercentage,{decimals:3})}/><Stat label="OPS" value={formatStat(stats.ops,{decimals:3})}/><Stat label="HR" value={formatStat(stats.homeRuns)}/><Stat label="RBI" value={formatStat(stats.rbi)}/><Stat label="SB" value={formatStat(stats.stolenBases)}/><Stat label="WALKS" value={formatStat(stats.walks)}/><Stat label="STRIKEOUTS" value={formatStat(stats.strikeouts)}/><Stat label="BB% / K%" value={`${formatStat(stats.walkRate,{decimals:1,percent:true})} / ${formatStat(stats.strikeoutRate,{decimals:1,percent:true})}`}/></>:stats?.kind==="pitching"?<><Stat label="G / GS" value={`${formatStat(stats.games)} / ${formatStat(stats.gamesStarted)}`}/><Stat label="INNINGS" value={formatStat(stats.inningsPitched,{decimals:1})}/><Stat label="ERA" value={formatStat(stats.era,{decimals:2})}/><Stat label="WHIP" value={formatStat(stats.whip,{decimals:2})}/><Stat label="STRIKEOUTS" value={formatStat(stats.strikeouts)}/><Stat label="WALKS" value={formatStat(stats.walks)}/><Stat label="K% / BB%" value={`${formatStat(stats.strikeoutRate,{decimals:1,percent:true})} / ${formatStat(stats.walkRate,{decimals:1,percent:true})}`}/><Stat label="SAVES" value={formatStat(stats.saves)}/></>:<p className="profile-unavailable">Current-season statistics are unavailable. Identity data remains verified.</p>}</div></section>
      <section className="profile-section gem-profile"><div className="profile-section-head"><h2>Gem Score v1</h2>{hiddenGemRank&&<span>#{hiddenGemRank} HIDDEN GEM</span>}</div>{current?.gemScore!==null&&current?.gemScoreDetails?<><div className="profile-gem"><GemScore score={current.gemScore} size="lg"/><div>{current.gemScoreDetails.categories.map(c=><Stat key={c.key} label={c.label.toUpperCase()} value={c.score===null?"N/A":Math.round(c.score)} note={c.activeWeight===null?"Inactive":`${c.activeWeight.toFixed(0)}% weight`}/>)}</div></div><div className="profile-why"><h3>Why this Gem Score?</h3>{current.gemScoreDetails.positiveFactors.map(f=><p key={f.metric}>+ {f.description}</p>)}{current.gemScoreDetails.limitingFactors.map(f=><p key={f.metric}>− {f.description}</p>)}</div></>:<p className="profile-unavailable">{current?.gemScoreDetails?.sampleStatus??"Current statistics are unavailable, so Gem Score eligibility cannot be determined."}</p>}</section></div>
    <section className="profile-section"><div className="profile-section-head"><h2>Defense</h2><span>STANDARD FIELDING</span></div><div className="profile-stat-grid"><Stat label="PRIMARY POSITION" value={current?.defense.primaryPosition??identity.position}/><Stat label="GAMES / INNINGS" value={`${formatStat(current?.defense.games??null)} / ${formatStat(current?.defense.innings??null,{decimals:1})}`}/><Stat label="ERRORS" value={formatStat(current?.defense.errors??null)}/><Stat label="FIELDING %" value={formatStat(current?.defense.fieldingPercentage??null,{decimals:3})}/><Stat label="OAA / DRS" value="N/A / N/A"/><Stat label="DEFENSIVE WAR" value="N/A"/><Stat label="GOLD GLOVES" value="N/A"/></div><p className="profile-source"><Shield/> Advanced defensive and awards sources are not connected.</p></section>
    <section className="profile-section"><div className="profile-section-head"><h2>Career / Season History</h2><span>{career.length} MLB SEASONS</span></div><div className="career-table-wrap"><table className="career-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{career.slice().reverse().map(s=><tr key={`${s.season}-${s.team}`}><td>{s.season}</td><td>{s.team??"N/A"}</td><td>{s.age??"N/A"}</td><td>{s.games??"N/A"}</td>{isHitter?<><td>{s.plateAppearances??"N/A"}</td><td>{s.avg?.toFixed(3).replace(/^0/,"")??"N/A"}</td><td>{s.obp?.toFixed(3).replace(/^0/,"")??"N/A"}</td><td>{s.slg?.toFixed(3).replace(/^0/,"")??"N/A"}</td><td>{s.ops?.toFixed(3).replace(/^0/,"")??"N/A"}</td><td>{s.homeRuns??"N/A"}</td><td>{s.rbi??"N/A"}</td><td>{s.stolenBases??"N/A"}</td></>:<><td>{s.starts??"N/A"}</td><td>{s.inningsPitched??"N/A"}</td><td>{s.era?.toFixed(2)??"N/A"}</td><td>{s.whip?.toFixed(2)??"N/A"}</td><td>{s.strikeouts??"N/A"}</td><td>N/A</td><td>{s.saves??"N/A"}</td></>}</tr>)}</tbody></table></div><p className="profile-source"><Award/> Historical standard statistics supplied by MLB Stats API. Unsupported values remain N/A.</p></section>
  </div>
}
