import { ProspectDirectory, type ProspectDirectoryRow } from "@/components/prospect-directory";
import { Eyebrow } from "@/components/ui";
import { fetchProspectDataset } from "@/data/providers/mlb-milb-provider";

export default async function ProspectsPage(){
  const data=await fetchProspectDataset().catch(()=>null),organizations=Array.from(new Set(data?.players.map(player=>player.organization).filter((value):value is string=>Boolean(value))??[])).sort(),organizationIndex=new Map(organizations.map((organization,index)=>[organization,index]));
  const directory:ProspectDirectoryRow[]=data?.players.map(player=>{const performance=Math.max(-1,...player.statLines.filter(line=>line.role==="hitter").map(line=>line.ops??-1));return[player.playerId,player.name,player.organization?organizationIndex.get(player.organization)??-1:-1,player.affiliate.abbreviation,player.level,player.position,player.role,player.age,performance<0?null:performance]})??[];
  return <div className="subpage page-width"><header className="page-header"><div><Eyebrow>AFFILIATED BASEBALL DIRECTORY</Eyebrow><h1>Minor League <em>Prospects</em></h1><p>Official identities, affiliates, levels, and current-season performance.</p></div>{data&&<div className="updated"><span>DATASET</span><strong>{data.players.length} PLAYERS</strong><small className={data.stale?"source-fallback":"source-live"}>● {data.stale?"STALE CACHE":"MLB / MiLB DATA"}</small></div>}</header>{data?<><div className="freshness-note">Stats updated {new Date(data.refreshedAt).toLocaleString()} · {data.teams.length} affiliates · Prospect Gem Score not yet implemented</div><ProspectDirectory rows={directory} organizations={organizations}/></>:<div className="empty-state">MiLB data is temporarily unavailable. No fabricated fallback was substituted.</div>}</div>;
}
