import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { canDelete,canEdit,canPublish,getContributor } from "@/data/articles/auth";
import { findArticle } from "@/data/articles/repository";
import { createSupabaseServerClient } from "@/data/articles/supabase";
import { ArticleValidationError,parseArticleInput,slugify } from "@/data/articles/validation";

export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){try{const identity=await getContributor(),{id}=await params;if(!identity)return NextResponse.json({error:"Unauthorized."},{status:401});const existing=await findArticle(id);if(!existing)return NextResponse.json({error:"Article not found."},{status:404});if(!canEdit(identity,existing))return NextResponse.json({error:"Forbidden."},{status:403});const input=parseArticleInput(await request.json());if(input.status==="published"&&!canPublish(identity.role))return NextResponse.json({error:"Your role cannot publish articles."},{status:403});const client=await createSupabaseServerClient();if(!client)return NextResponse.json({error:"Publishing is not configured."},{status:503});const updatedSlug=slugify(input.slug||existing.slug);const{error}=await client.from("articles").update({title:input.title,slug:updatedSlug,excerpt:input.excerpt,content:input.content,cover_image_url:input.coverImageUrl,image_alt:input.imageAlt,status:input.status,category:input.category,tags:input.tags,related_player_id:input.relatedPlayerId,related_team_id:input.relatedTeamId,seo_title:input.seoTitle,seo_description:input.seoDescription,published_at:input.status==="published"?(existing.publishedAt??new Date().toISOString()):null}).eq("id",id);if(error)return NextResponse.json({error:error.code==="23505"?"That slug is already in use.":"Article could not be updated."},{status:409});revalidatePath("/");revalidatePath("/analysis");revalidatePath(`/analysis/${existing.slug}`);revalidatePath(`/analysis/${updatedSlug}`);return NextResponse.json({id,slug:updatedSlug})}catch(error){return NextResponse.json({error:error instanceof ArticleValidationError?error.message:"Invalid article."},{status:400})}}

export async function DELETE(_request:Request,{params}:{params:Promise<{id:string}>}){const identity=await getContributor(),{id}=await params;if(!identity)return NextResponse.json({error:"Unauthorized."},{status:401});const existing=await findArticle(id);if(!existing)return NextResponse.json({error:"Article not found."},{status:404});if(!canDelete(identity,existing))return NextResponse.json({error:"Your role cannot delete this article."},{status:403});const client=await createSupabaseServerClient();if(!client)return NextResponse.json({error:"Publishing is not configured."},{status:503});const{error}=await client.from("articles").delete().eq("id",id);if(error)return NextResponse.json({error:"Article could not be deleted."},{status:409});revalidatePath("/");revalidatePath("/analysis");revalidatePath(`/analysis/${existing.slug}`);return NextResponse.json({ok:true},{headers:{"cache-control":"no-store"}})}
